//------------------------------------------------------------------------------ GroupChatJoin
A[0].u.chat.getGroups((x,r) =>
  (x) ? log(a, 'FAILURE | getGroups ' + (x.message).yellow)
  :(((inchat = Object.entries(r.chat_room_groups).filter(e => e[1].group_summary.clanid != null).map(e => e[1].group_summary.clanid.toString())) => (
    group_chat_join_array = Object.keys(A[0].u.myGroups).filter(e => !inchat.includes(e) && A[0].u.myGroups[e] == 3)))()));
group_chat_join_index = -1,
group_chat_join_delay = 30000,
group_chat_join = (h = group_chat_join_array[++group_chat_join_index]) => (
  A[0].u.chat.getClanChatGroupInfo(h, (x, b) => (
    (b.chat_group_summary.active_member_count < 1) ?
      console.log('skipping: https://steamcommunity.com/gid/' + h)
    :(console.log('joining chat: https://steamcommunity.com/gid/' + h),
      A[0].u.chat.joinGroup(b.chat_group_summary.chat_group_id)),
    setTimeout(group_chat_join, group_chat_join_delay)))) 
//------------------------------------------------------------------------------ GroupInfoGather
groups = Object.keys(A[0].u.myGroups).filter(e => A[0].u.myGroups[e] == 3),
group_delay = 1500,
group_ids = {};
group_avatars = {};
get_group_id = (i) =>
  http(A[0], 'gid/' + groups[i], null, (b, r, x) =>
    (i < groups.length) && (
      setTimeout(get_group_id, group_delay, i+1),
      (b.includes('Join Group')) ?
        console.log('unjoined: ' + groups[i])
      :(group_avatars[groups[i]] = b.match(/[a-z0-9]+_full/)[0],
        group_ids[groups[i]] = b.match(/Clan_103[0-9]+/)[0].substr(5))))
//------------------------------------------------------------------------------ GroupKickAttempts
http(A[0], 'https://steamcommunity.com/gid/2751860/banuser/?ajax=1', {
  gidforum: -1, gidtopic: -1, gidcomment: '', target: 109261560, is_warning: 0, ban_length: 0, ban_reason: ''});
A[0].u.chat.setGroupUserBanState(A[0].chat[0], '76561198355133802', true, (x, r) => console.dir(x))
http(A[0], 'https://steamcommunity.com/groups/primarydataloop/chatBanManage', { xml: 1, action: 'ban', steamId: 109261560 })
//------------------------------------------------------------------------------ DeprecatedGroupForms
((group_url = profile.group_favorite.selection[0].substr(19)) =>
  http(accounts[0], 'groups/' + group_url + '/edit', '&' + data.group_forms[group_url].replace(
    /&headline=.*&summary=/, '&headline=' + generate_emoji_fortune(215) + '&summary=')))(),  
"group_forms": {
  "fourteenpdl": "type=profileSave&abbreviation=fourteenpdl&headline=%F0%9F%8C%B3+Actor+Real+Name+Boris+Karloff+%F0%9F%8C%82+William+Henry+Pratt+Cary+%F0%9F%93%80+Grant+Archibald+Leach+Edward+%F0%9F%93%98+G.+Robinson+Emmanual+Goldenburg+%F0%9F%98%BA+Gene+Wilder+Gerald+Silberman+%F0%9F%8D%A7+John+Wayne+Marion+Morrison+%F0%9F%8F%80+Kirk+Douglas+Issur+Danielovitch+Richard++%F0%9F%8E%8D&summary=&customURL=fourteenpdl&language=norwegian&country=NA&state=27&city=&associate_game=&favorite_games=450390&weblink_1_title=Equal+Reality+-+DMX+Krew+%7BHTC+VIVE+VR%7D&weblink_1_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DkJlPZlYuRPU&weblink_2_title=Magic+Lantern+-+808+State+%7BHTC+VIVE+VR%7D&weblink_2_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Dfm9T_a7tqeE&weblink_3_title=Project+Syria+-+%7BHTC+VIVE+VR%7D&weblink_3_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DCgSHiLcgtAo",
  "seispdl": "type=profileSave&abbreviation=seispdl&headline=%F0%9F%92%83+Slaves+are+generally+expected+to+sing+%F0%9F%91%BE+as+well+as+to+work+%F0%9F%8C%B3+...+I+did+not%2C+when+%F0%9F%90%9D+a+slave%2C+understand+the+deep+%F0%9F%93%98+meanings+of+those+rude%2C+and+%F0%9F%95%BA+apparently+incoherent+songs.+I+was+%F0%9F%8C%8B+myself+within+the+circle%2C+so+that+I+neither+%F0%9F%8D%87&summary=&customURL=seispdl&language=finnish&country=BL&state=&city=&associate_game=&favorite_games=555160&weblink_1_title=MSI+Electric+City%2C+Core+Assault+-+%7BHTC+VIVE+VR%7D&weblink_1_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D5-kmNpokbBQ&weblink_2_title=Amazing+Files%2C+Horror+Hospital+-+Biosphere+%7BHTC+VIVE+VR%7D&weblink_2_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DJQTDBM8J90c&weblink_3_title=Lucky+Night%2C+Texas+Hold'em+-+Luke+Vibert+%7BHTC+VIVE+VR%7D&weblink_3_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DfFvLKzck1nw",
  "pdlproper3": "type=profileSave&abbreviation=pdlproper3&headline=%F0%9F%90%A0+No-one+would+have+believed%2C+in+the+%F0%9F%9A%98+final+years+of+the+Century+%F0%9F%93%80+of+the+Fruitbat%2C+that+Discworld+%F0%9F%92%9A+affairs+were+being+watched+keenly+%F0%9F%8F%93+and+impatiently+by+intelligences+greater+%E2%9A%A1+than+Man's%2C+or+at+least+%F0%9F%8E%8D+much+nastier%3B+that++%F0%9F%90%B3&summary=&customURL=pdlproper3&language=danish&country=DK&state=04&city=&associate_game=&favorite_games=607440&weblink_1_title=Covert+Syndrome+-+Binalog+Frequency+%7BHTC+VIVE+VR%7D&weblink_1_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D8ll4hFleRzw&weblink_2_title=Deserving+Life+-+Frontline+Assembly+%7BHTC+VIVE+VR%7D&weblink_2_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Dk9cgeq8Yx_Q&weblink_3_title=Deserving+Life+-+Frontline+Assembly+%7BHTC+VIVE+VR%7D&weblink_3_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D1rqyPqw_LCk",
  "pdl15": "type=profileSave&abbreviation=pdl15&headline=%F0%9F%93%92+A+sharper+perspective+on+this+%F0%9F%A5%97+matter+is+particularly+important+%F0%9F%9A%97+to+feminist+thought+today%2C+%F0%9F%91%BE+because+a+major+tendency+%F0%9F%91%94+in+feminism+has+constructed+%E2%9B%B3+the+problem+of+domination+%F0%9F%91%83+as+a+drama+of+female+vulnerability+victimiz+%F0%9F%8E%88&summary=&customURL=pdl15&language=polish&country=PK&state=04&city=&associate_game=&favorite_games=606180&weblink_1_title=Discover+Egypt%2C+King+Tut's+Tomb+-+Egyptian+Lover+%7BHTC+VIVE+VR%7D&weblink_1_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DJN-comON924&weblink_2_title=ViveSpray+-+Fah+%7BHTC+VIVE+VR%7D&weblink_2_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DnmcXAYyTMx0&weblink_3_title=Pavlov+-+Democracy+Now+%7BHTC+VIVE+VR%7D&weblink_3_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DWS_OlV6N-4I",
  "pdlocho": "type=profileSave&abbreviation=pdlocho&headline=%F0%9F%A5%92+In+%22King+Henry+VI%2C+Part+II%2C%22+%F0%9F%8D%A7+Shakespeare+has+Dick+Butcher+suggest+%F0%9F%8E%AB+to+his+fellow+anti-establishment+rabble-rousers%2C+%F0%9F%9A%95+%22The+first+thing+we+do%2C+%F0%9F%8C%B3+let's+kill+all+the+lawyers.%22+%F0%9F%8C%82+That+action+may+be+extreme+%F0%9F%94%8B+but+a+similar+sen+%F0%9F%90%B3&summary=&customURL=pdlocho&language=&country=&state=&city=&associate_game=&favorite_games=436320&weblink_1_title=InVR+-+Computron+%7BHTC+VIVE+VR%7D&weblink_1_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DJe9zsJWPikY&weblink_2_title=Butts+%7BHTC+VIVE+VR%7D&weblink_2_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DddtkOkEbYxw&weblink_3_title=Suspended+Workshops+-+Biosphere+%7BHTC+VIVE+VR%7D&weblink_3_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DBP59gcwbK2o",
  "quatropdl": "type=profileSave&abbreviation=quatropdl&headline=%F0%9F%8C%B8+One+fine+day%2C+the+bus+driver+went+%F0%9F%93%A3+to+the+bus+garage%2C+started+his+%F0%9F%93%92+bus%2C+and+drove+off+along+the+%F0%9F%9A%99+route.+No+problems+for+the+first+%F0%9F%8D%A7+few+stops+--+a+few+people+%F0%9F%8F%93+got+on%2C+a+few+got+off%2C+%E2%9B%B3+and+things+went+generally+well.+At+t+%F0%9F%91%83&summary=&customURL=quatropdl&language=dutch&country=NO&state=09&city=&associate_game=&favorite_games=348250&weblink_1_title=Super+Hot+-+Phil+Klein+%7BHTC+VIVE+VR%7D&weblink_1_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DT9pPqKdxQxM&weblink_2_title=TSA+Frisky+-+Automatic+Tasty+%7BHTC+VIVE+VR%7D&weblink_2_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Dky6-_sBcvig&weblink_3_title=Disco+Destruction+-+Global+Goon+%7BHTC+VIVE+VR%7D&weblink_3_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DRAkQ-DE9rAc",
  "sevenpdlteen": "type=profileSave&abbreviation=sevenpdlteen&headline=%F0%9F%93%95+MAFIA%2C+n%3A+%5BAcronym+for+Mechanized+%F0%9F%8C%B3+Applications+in+Forced+Insurance+%F0%9F%8D%87+Accounting.%5D+An+extensive+network+%F0%9F%A5%97+with+many+on-line+and+%F0%9F%93%80+offshore+subsystems+running+under+%F0%9F%92%84+OS%2C+DOS%2C+and+IOS.+%E2%9B%B3+MAFIA+documentation+is+rather+scanty%2C+%F0%9F%8F%80&summary=&customURL=sevenpdlteen&language=brazilian&country=PS&state=&city=&associate_game=&favorite_games=490490&weblink_1_title=Imos+Loft+-+Electronome+%7BHTC+VIVE+VR%7D&weblink_1_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Dt0MmMBT1E6k&weblink_2_title=Sommad+-+CN+%7BHTC+VIVE+VR%7D&weblink_2_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DUIf5wUC_tWI&weblink_3_title=Pararea+-+DeFeKT+%7BHTC+VIVE+VR%7D&weblink_3_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DU2CZR_KAd5M",
  "pdl8teen": "type=profileSave&abbreviation=pdl8teen&headline=%F0%9F%93%92+River%3A%3A+%22We+got+outflanked+by+an+%F0%9F%90%8A+Independent+squad%2C+and+we're+never+%F0%9F%91%94+gonna+make+it+back+to+%F0%9F%8E%88+our+platoon.+We+need+to+%F0%9F%8C%B3+resort+to+cannibalism.%22+Simon%3A+%22That+%F0%9F%8F%93+was+fast.+Don't+we+have+%F0%9F%8D%A7+rations+or+anything%3F%22+River%3A+%22They+go+%F0%9F%98%BA&summary=&customURL=pdl8teen&language=russian&country=RE&state=&city=&associate_game=&favorite_games=568800&weblink_1_title=Summer+Times+Afternoon+-+Lee+Norris+%7BHTC+VIVE+VR%7D&weblink_1_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DEJnYFkeDpig&weblink_2_title=BattleDome+-+Headnoaks+%7BHTC+VIVE+VR%7D&weblink_2_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DM_GCWxhMUxU&weblink_3_title=Dead+Hungry+-+Radioactive+Man+%7BHTC+VIVE+VR%7D&weblink_3_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Dfl5x5t8Q224",
  "twopdl": "type=profileSave&abbreviation=twopdl&headline=%F0%9F%8C%BD+Darth+Vader%3A+There+is+no+escape.+%F0%9F%92%97+Don't+make+me+destroy+you.+%F0%9F%95%BA+pauses+Luke%2C+you+do+not+%F0%9F%8C%8F+yet+realize+your+importance.+You+%F0%9F%93%95+have+only+begun+to+discover+%F0%9F%91%83+your+power.+Join+me%2C+and+%F0%9F%90%9F+I+will+complete+your+training.+With+our+co+%F0%9F%90%8A&summary=&customURL=twopdl&language=czech&country=CA&state=PE&city=&associate_game=&favorite_games=469610&weblink_1_title=MeiMei+Dance+-+Hashim+%7BHTC+VIVE+VR%7D&weblink_1_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D6l4qPhrABWM&weblink_2_title=Basketball+Babe+-+Kerrier+District+%7BHTC+VIVE+VR%7D&weblink_2_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Dl4aDpK4BL4Y&weblink_3_title=Munch+-+UHU+%7BHTC+VIVE+VR%7D&weblink_3_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DG2H5XuY1j9s",
  "diezytrespdl": "type=profileSave&abbreviation=diezytrespdl&headline=%F0%9F%8C%8B+A+disciple+of+another+sect+once+%F0%9F%91%BD+came+to+Drescher+as+he+%F0%9F%93%98+was+eating+his+morning+meal.+%F0%9F%8D%87+%22I+would+like+to+give+%F0%9F%90%9B+you+this+personality+test%22%2C+said+%F0%9F%8C%82+the+outsider%2C+%22because+I+want+%F0%9F%92%9B+you+to+be+happy.%22+Drescher+took+the+paper+t+%F0%9F%92%9A&summary=&customURL=diezytrespdl&language=koreana&country=KZ&state=07&city=&associate_game=&favorite_games=511690&weblink_1_title=Duck+Force+-+Planetwalker+%7BHTC+VIVE+VR%7D&weblink_1_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D9vN4JdSvE1Y&weblink_2_title=Battleship+Yamato+-+Slavoj+Zizek+%7BHTC+VIVE+VR%7D&weblink_2_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DGIO4_Kd2quY&weblink_3_title=The+Purge+Day+-+Galaxion+%7BHTC+VIVE+VR%7D&weblink_3_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Dbnc9EUFYI_s",
  "funfpdl": "type=profileSave&abbreviation=funfpdl&headline=%F0%9F%92%99+Sister+Mary+headed+through+the+night-time+%F0%9F%92%84+hospital+with+the+Adversary%2C+Destroyer+%F0%9F%A5%9E+of+Kings%2C+Angel+of+the+%F0%9F%A5%92+Bottomless+Pit%2C+Great+Beast+that+%E2%9A%A1+is+called+Dragon%2C+Prince+of+%F0%9F%93%95+This+World%2C+Father+of+Lies%2C+%F0%9F%8D%86+Spawn+of+Satan+and++%F0%9F%95%BA&summary=&customURL=funfpdl&language=english&country=EC&state=09&city=&associate_game=&favorite_games=525640&weblink_1_title=Unreal+Villa+-+Paco+Osuna+%7BHTC+VIVE+VR%7D&weblink_1_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DhKQn5BTXWQ8&weblink_2_title=Altspace+-+Elysis+%7BHTC+VIVE+VR%7D&weblink_2_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DWSHNQi3lTzE&weblink_3_title=EmbodyME+-+MC+Hawking+%7BHTC+VIVE+VR%7D&weblink_3_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DFLDI3jgXwbg",
  "10pdl": "type=profileSave&abbreviation=10pdl&headline=%F0%9F%8D%A7+Too+Late+A+large+number+of+%F0%9F%8C%8B+turkies+%5Bsic%5D+went+to+San+%F0%9F%8C%B3+Francisco+yesterday+by+the+two+%F0%9F%93%95+o'clock+boats.+If+their+object+%E2%9A%A1+in+going+down+was+to+%F0%9F%8E%AB+participate+in+the+Thanksgiving+festivities+%F0%9F%92%84+of+that+city%2C+they+would+arrive++%F0%9F%95%BA&summary=&customURL=10pdl&language=hungarian&country=MO&state=02&city=&associate_game=&favorite_games=&weblink_1_title=Hop+Step+Sing!+Kimamani+Summer+Vacation+-+Afrika+Bambaataa+%7BHTC+VIVE+VR%7D&weblink_1_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Dt-eypU4jqqI&weblink_2_title=Trespass+-+James+Stinson+%7BHTC+VIVE+VR%7D&weblink_2_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DBPv0T6r_lpw&weblink_3_title=Mister+Mart+-+Group+X+%7BHTC+VIVE+VR%7D&weblink_3_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DOO8_gkcxRYg",
  "elevenpdl": "type=profileSave&abbreviation=elevenpdl&headline=%F0%9F%92%99+Charles+Briscoe-Smith+%3Ccpbs%40debian.org%3E%3A+After+%E2%9A%A1+all%2C+the+gzip+%F0%9F%92%83+package+is+called+%E2%9B%B3+%60gzip'%2C+not+%60libz-bin'...+%F0%9F%93%A3+James+Troup+%3Ctroup%40debian.org%3E%3A+%F0%9F%9A%99+Uh%2C+probably+because+%F0%9F%91%94+the+gzip+binary+doesn't+come+from+the+non-existent+lib+%F0%9F%93%95&summary=&customURL=elevenpdl&language=italian&country=IS&state=13&city=&associate_game=&favorite_games=471710&weblink_1_title=Kiya+-+Luis+Ruiz+%7BHTC+VIVE+VR%7D&weblink_1_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DFB6W_U5o9L4&weblink_2_title=Triber+-+Dez+Williams+%7BHTC+VIVE+VR%7D&weblink_2_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DkZLYfitOK30&weblink_3_title=Vee+Rethak%2C+Deep+Under+the+Mountain+-+Cybrid+%7BHTC+VIVE+VR%7D&weblink_3_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DCb80ydB89T4",
  "dozenpdl": "type=profileSave&abbreviation=dozenpdl&headline=%F0%9F%8C%B3+(Mal%2C+fighting+with+his+torturer+on+%F0%9F%8E%88+the+edge+of+the+factory+%E2%9A%A1+shaft+precipice%2C+is+interrupted+by+%F0%9F%8C%8B+the+arrival+of+his+crew.+%F0%9F%91%BD+Jayne+lifts+his+gun%2C+and+%F0%9F%92%8E+takes+aim%3B+however%2C+Zoe+grabs+%F0%9F%98%BA+his+arm.)+Zoe%3A+%22This+is+something+the+%F0%9F%9A%95&summary=&customURL=dozenpdl&language=japanese&country=JM&state=04&city=&associate_game=&favorite_games=440630&weblink_1_title=A-Tech+Cybernetic+-+Chris+Hayes+%7BHTC+VIVE+VR%7D&weblink_1_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Dwe_tQ-KM1_E&weblink_2_title=The+Price+of+Freedom+%7BHTC+VIVE+VR%7D&weblink_2_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DhyGNtsrUZqc&weblink_3_title=Paranormal+Activity+-+%7BHTC+VIVE+VR%7D&weblink_3_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DPoTrn-UwtpU",
  "pdluno": "type=profileSave&abbreviation=pdluno&headline=%F0%9F%8F%80+Q%3A+How+many+elephants+can+you+fit+in+%F0%9F%8C%B3+a+VW+Bug%3F+A%3A+Four.+Two+in+%F0%9F%8F%93+the+front%2C+two+in+the+back.+Q%3A+%F0%9F%9A%98+How+can+you+tell+if+an+elephant+%F0%9F%9A%99+is+in+your+refrigerator%3F+A%3A+There's+a+%F0%9F%91%91+footprint+in+the+mayo.+Q%3A+How+can+%F0%9F%8E%AB+you+tell+if+tw+%F0%9F%91%B9&summary=&customURL=pdluno&language=bulgarian&country=BB&state=09&city=&associate_game=&favorite_games=438100&weblink_1_title=Engage+-+%7BHTC+VIVE+VR%7D&weblink_1_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DIDIzspUokCw&weblink_2_title=Accounting+%7BHTC+VIVE+VR%7D&weblink_2_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DNcFyPUwFPNs&weblink_3_title=Disco+Time+80s+-+%7BHTC+VIVE+VR%7D&weblink_3_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Dq8HZ8q8nxbs",
  "pneindteenl": "type=profileSave&abbreviation=pneindteenl&headline=%F0%9F%8C%B8+7%3A30%2C+Channel+5%3A+The+Bionic+%F0%9F%93%97+Dog+(Action%2FAdventure)+The+Bionic+%F0%9F%91%B3+Dog+drinks+too+much+%F0%9F%8E%BD+and+kicks+over+the+%F0%9F%91%94+National+Redwood+Forest.+7%3A30%2C+%F0%9F%90%9B+Channel+8%3A+The+Bionic+%F0%9F%8D%96+Dog+(Action%2FAdventure)+The+Bionic+Dog+gets+a+hormonal+shor+%F0%9F%91%83&summary=&customURL=pneindteenl&language=schinese&country=KH&state=14&city=&associate_game=&favorite_games=672020&weblink_1_title=The+Ruins%2C+Escape+the+Room+-+David+Frum+%7BHTC+VIVE+VR%7D&weblink_1_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Du4tGT1bZXcQ&weblink_2_title=Hold+My+Beer+-+Exzakt+%7BHTC+VIVE+VR%7D&weblink_2_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D2s9HJ0bKqWg&weblink_3_title=Cirque+du+Soleil+-+%7BHTC+VIVE+VR%7D&weblink_3_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D-uh7CZO8Kfk",
  "neinpdl": "type=profileSave&abbreviation=neinpdl&headline=%F0%9F%92%84+Hell+Money%3A+Mulder%3A+How+many+dishes+%F0%9F%91%94+do+you+have+to+break+%F0%9F%94%8B+before+your+boss+tosses+you+%F0%9F%93%92+in+an+oven%3F+Scully%3A+So+%F0%9F%8E%8D+now+we're+chasing+ghosts%3F+Mulder%3A+%F0%9F%91%B9+Who+ya+gonna+call%3F+Scully%3A+%F0%9F%92%99+Are+you+saying+that+the+ancestral+spirits+p+%F0%9F%A5%9E&summary=&customURL=neinpdl&language=greek&country=GA&state=05&city=&associate_game=&favorite_games=490840&weblink_1_title=Rich+Life+Simulator+-+Donald+Trump+%7BHTC+VIVE+VR%7D&weblink_1_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Dyasz5mRdCVk&weblink_2_title=The+Uncertain+Experience+-+Ditone+%7BHTC+VIVE+VR%7D&weblink_2_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DWGf_MztMJOM&weblink_3_title=Hotdogs%2C+Horseshoes%2C+and+Hand+Grenades+-+Clarence+G+%7BHTC+VIVE+VR%7D&weblink_3_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DASnVnr9A3iM",
  "7pdl": "type=profileSave&abbreviation=7pdl&headline=%F0%9F%8E%8D+You+know+you're+in+trouble+when...+(1)+%F0%9F%90%A0+Your+car+horn+goes+off+accidentally+%F0%9F%92%9A+and+remains+stuck+as+you+follow+%F0%9F%8E%BD+a+group+of+Hell's+Angels+on+%F0%9F%8C%8B+the+freeway.+(2)+You+want+to+%F0%9F%90%9D+put+on+the+clothes+you+wore+%F0%9F%9A%98+home+from+the+party++%F0%9F%9A%97&summary=&customURL=7pdl&language=french&country=FK&state=&city=&associate_game=&favorite_games=418650&weblink_1_title=Duck+Season+-+%7BHTC+VIVE+VR%7D&weblink_1_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DzTxBO5jbyww&weblink_2_title=El+Ministerio+del+Tiempo%2C+El+Tiempo+en+tus+Manos+-+%7BHTC+VIVE+VR%7D&weblink_2_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D_5MbfQULReM&weblink_3_title=Dear+Angelica+-+%7BHTC+VIVE+VR%7D&weblink_3_url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D0LGH6LlTDdc",
  "psixdteenl": "type=profileSave&abbreviation=psixdteenl&headline=%F0%9F%8E%84+%5BThe+Kennedy+Assassinations%5D+%22Sometime+later+-+%F0%9F%90%A0+FOR+NO+PARTICULAR+REASON+-+%F0%9F%8E%AB+somebody+shot+that+nice+young+%F0%9F%98%BA+president+when+he+was+riding+%F0%9F%9A%97+in+his+car+and+a+%F0%9F%93%98+few+years+after+that%2C+somebody+%F0%9F%93%80+shot+his+little+brother+too+-+o+%F0%9F%8E%8D&summary=&customURL=psixdteenl&language=portuguese&country=PW&state=&city=&associate_game=&favorite_games=665200&weblink_1_title=&weblink_1_url=&weblink_2_title=&weblink_2_url=&weblink_3_title=&weblink_3_url=" },
edit_group = (group, text) => {
  http_request('groups/' + group + '/edit', {}, (body, response, err) => {
    var data = Cheerio.load(body)("#editForm").serializeArray();
    data[3].value = text;
    http_request('groups/' + group + '/edit', data);
  });
}